payment:
  providers:
    vnpay:
      terminal-code: "${VNPAY_TMN_CODE}"
      hash-secret: "${VNPAY_HASH_SECRET}"
      pay-url: "${VNPAY_PAY_URL}"
      return-url: "${FRONTEND_BASE_URL}/${VNPAY_RETURN_PATH_FORMAT}"
      username: "${VNPAY_USERNAME}"
      payment-timeout: "${VNPAY_PAYMENT_TIMEOUT}"
