payment:
  providers:
    vnpay:
      terminal-code: "${VNPAY_TMN_CODE}"
      hash-secret: "${VNPAY_HASH_SECRET}"
      pay-url: "${VNPAY_PAY_URL}"
      return-url: "${VNPAY_RETURN_URL}"
      username: "${VNPAY_USERNAME}"
