server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${SERVER_BASE_PATH}
  error:
    include-message: always
    include-binding-errors: always
  compression:
    enabled: true

spring:
  web:
    resources:
      add-mappings: false

  application:
    name: car-rental-system

  datasource:
    url: "jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: "${DB_POOL_MAX_SIZE}"
      minimum-idle: "${DB_POOL_MIN_IDLE}"
      connection-timeout: 20000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
      validation-timeout: 5000
      initialization-fail-timeout: 1
      pool-name: HikariPool-${spring.application.name}

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

  jpa:
    hibernate:
      ddl-auto: "${JPA_DDL_AUTO}"
    show-sql: "${JPA_SHOW_SQL}"
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  mail:
    host: "${MAIL_SMTP_HOST}"
    port: "${MAIL_SMTP_PORT}"
    username: "${MAIL_USERNAME}"
    password: "${MAIL_PASSWORD}"
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          timeout: 5000
          connectiontimeout: 5000
          writetimeout: 5000
      debug: "${MAIL_DEBUG}"

  servlet:
    multipart:
      max-file-size: "${UPLOAD_MAX_FILE_SIZE}"
      max-request-size: "${UPLOAD_MAX_REQUEST_SIZE}"
      enabled: true

  config:
    import:
      - classpath:config/otp.yml
      - classpath:config/cloudinary.yml
      - classpath:config/security.yml
      - classpath:config/health.yml
      - classpath:config/payment.yml
